services:
  # payload:
  #   image: node:alpine
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/home/node/app
  #     - node_modules:/home/node/app/node_modules
  #   working_dir: /home/node/app/
  #   command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
  #   depends_on:
  #     - postgres
  #     # - mongo
  #   env_file:
  #     - .env
  # Ensure your DATABASE_URI uses 'mongo' as the hostname ie. mongodb://mongo/my-db-name
  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - '27017:27017'
  #   command:
  #     - --storageEngine=wiredTiger
  #   volumes:
  #     - mongodata:/data/db
  #   logging:
  #     driver: none
  #   env_file:
  #     - .env

  # Uncomment the following to use postgres
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "15433:80"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - pgadmindata:/var/lib/pgadmin/
volumes:
  # mongodata:
  pgdata:
  pgadmindata:
  node_modules:
